Repository seismo-learn/seismology101, pull requests merged in 2021-04, with the labels that each got.

#233 Fix bad link of Rufus
  source/computer/fedora-setup.rst
  source/computer/ubuntu-setup.rst
Labels: bug, linux

#230 Tiny fix
  source/computer/commands.rst
Labels: linux

#227 Add .zshrc in Intel oneapi warning
  source/computer/intel-oneapi-warning.rst_
Labels: linux, macOS

#228 Rename Chinese translation for introduction
  source/best-practices/introduction.rst
  source/index.rst
  source/programming/introduction.rst
  source/seismology/introduction/index.rst
Labels: maintance

#229 Add resources for the programming parts
  source/programming/bash.rst
  source/programming/c.rst
  source/programming/compile.rst
  source/programming/fortran.rst
  source/programming/python.rst
  source/programming/version-control.rst
Labels: programming

#231 Operating systems: improve the documentation
  source/computer/operating-system.rst
Labels: documentation, linux, macOS

#317 Improve the section of file permission
  source/computer/file-operations.rst
Labels: linux

#292 Seismology: Add an introduction to Seismology
  source/seismology/introduction.rst
  source/seismology/seismic-waves.jpg
Labels: seismology
